title: Mohammad [Portfolio]
#logo: /assets/img/measureoncecuttwice.png
image: /assets/images/measureoncecuttwice.png
description: Senior Data Engineer | Integration Lead | Functional Lead
show_downloads: false
theme: jekyll-theme-minimal
remote_theme: dracula/gh-pages

